### PR TITLE
Add anti-D0 logic

### PR DESCRIPTION
**Pull request by bainbrid**
Please see attached slide for details. 

[220916_Anti_D0_logic.pdf](https://github.com/DiElectronX/BParkingNANO/files/10006289/220916_Anti_D0_logic.pdf) (NOW OBSOLETE - SEE SLIDES BELOW!!)

### CODE REVIEW

**Comment by bainbrid** [comment]
@gkaratha @ottolau @gmelachr please check

**Comment by bainbrid** [comment]
@gkaratha @ottolau @gmelachr I know you're busy, but please can you scan quickly - make sense??

**Comment by bainbrid** [comment]
@jay-odedra

**Comment by ottolau** [comment]
Hi @bainbrid ,

Thanks for the PR! The code looks fine, but why the mass can be negative in the data? The invariant mass can't be negative since it is √p•p?

Best,
Otto

**Comment by bainbrid** [comment]
Hi @ottolau (@gkaratha @gmelachr)

ah yes, whoops ... !!

Now fixed: a5e1414376725b41ff2995fbd8034c354ede6ed9

Updated slides: 
[221114_Anti_D0_logic.pdf](https://github.com/DiElectronX/BParkingNANO/files/10006324/221114_Anti_D0_logic.pdf)

Now, the two masses are rather similar (and positive!). Is this as you expect? 

Both are kept in the NANOAOD so we cut on: min(mass1,mass2) > 2 GeV.

If you're happy, I'll merge ...

**Comment by ottolau** [comment]
Yes it looks good to me

**Pull request merged**
